version: "0.1"

services:
  db:
    container_name: core-db
    image: postgres:14.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
  backend:
    container_name: core-backend
    build:
      context: ./backend
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - "${API_PORT}:5000"
    environment:
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
      - TYPEORM_CONNECTION=${TYPEORM_CONNECTION}
      - TYPEORM_USERNAME=${TYPEORM_USERNAME}
      - TYPEORM_PASSWORD=${TYPEORM_PASSWORD}
      - TYPEORM_DATABASE=${TYPEORM_DATABASE}
      - TYPEORM_PORT=${TYPEORM_PORT}
      - TYPEORM_HOST=db
      - JWT_SECRET=${JWT_SECRET}
  frontend:
    container_name: core-frontend
    build:
      context: ./frontend
    depends_on:
      - backend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT}:3000"
